WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# ++++ Player
PLAYER_SIZE = 40
PLAYER_DAMAGE = 25
PLAYER_ARMOR = 5
PLAYER_MAX_HEALTH_POINTS = 100
PLAYER_COLOR = (255, 0, 0)
PLAYER_SPEED = 5
PLAYER_MAX_PROJECTILE_COUNT = 3

# Dash Ability
DASH_RANGE = 300 # px
DASH_DURATION = 60 # ticks
DASH_COOLDOWN_MAX = 180

# Projectile
PROJECTILE_SIZE = 8
PROJECTILE_SPEED = 8
PROJECTILE_PIERCING = 1

# Enemies
HITBOX_X_OFFSET = 5 # px
HITBOX_Y_OFFSET = 15 # px
HITBOX_WIDTH = 50
HITBOX_HEIGHT = 5


# Chaser
CHASER_DAMAGE = 8
CHASER_HEALTH_POINTS = 50
CHASER_MAX_HEALTH_POINTS = 50
CHASER_ARMOR = 10
CHASER_SPEED = 2
CHASER_SIZE = 30
CHASER_COLOR = (60, 195, 97)
CHASER_INITIAL_SPAWN_INTERVAL = 180 # frames
CHASER_MINIMAL_SPAWN_INTERVAL = 30

# Shooter
SHOOTER_HEALTH_POINTS = 50
SHOOTER_MAX_HEALTH_POINTS = 50
SHOOTER_ARMOR = 10
SHOOTER_DAMAGE = 10
SHOOTER_SIZE = 40
SHOOTER_SPEED = 2
SHOOTER_COLOR = (136, 38, 201)
SHOOTER_SHOOT_INTERVAL = 100
SHOOTER_INITIAL_SPAWN_INTERVAL = 500 # frames
SHOOTER_MINIMAL_SPAWN_INTERVAL = 120 # frames