WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# HUD
HUD_HEIGHT = 120
PLAY_AREA_HEIGHT = WINDOW_HEIGHT - HUD_HEIGHT



# ++++ Player
PLAYER_SIZE = 40
PLAYER_DAMAGE = 20
PLAYER_ARMOR = 5
PLAYER_MAX_HEALTH_POINTS = 100
PLAYER_COLOR = (255, 0, 0)
PLAYER_ATTACK_SPEED = 7
PLAYER_MOVEMENT_SPEED = 5
PLAYER_PROJECTILE_SIZE = 5

# Dash Ability
DASH_RANGE = 300 # px
DASH_DURATION = 30 # ticks
DASH_COOLDOWN_MAX = 90 # ticks

# Projectile
PROJECTILE_SIZE = 8
PROJECTILE_SPEED = 8
PROJECTILE_PIERCING = 3

# Enemies
HITBOX_X_OFFSET = 5 # px
HITBOX_Y_OFFSET = 15 # px
HITBOX_WIDTH = 50
HITBOX_HEIGHT = 5


# Chaser
CHASER_DAMAGE = 8
CHASER_HEALTH_POINTS = 45
CHASER_MAX_HEALTH_POINTS = 45
CHASER_ARMOR = 10
CHASER_ATTACK_SPEED = 0.5
CHASER_MOVEMENT_SPEED = 2
CHASER_SIZE = 30
CHASER_COLOR = (60, 195, 97)
CHASER_INITIAL_SPAWN_INTERVAL = 180 # frames
CHASER_MINIMAL_SPAWN_INTERVAL = 30

# Shooter
SHOOTER_HEALTH_POINTS = 30
SHOOTER_MAX_HEALTH_POINTS = 30
SHOOTER_ARMOR = 10
SHOOTER_DAMAGE = 10
SHOOTER_SIZE = 40
SHOOTER_ATTACK_SPEED = 0.25
SHOOTER_MOVEMENT_SPEED = 2
SHOOTER_COLOR = (136, 38, 201)
SHOOTER_SHOOT_INTERVAL = 100
SHOOTER_INITIAL_SPAWN_INTERVAL = 500 # frames
SHOOTER_MINIMAL_SPAWN_INTERVAL = 120 # frames

# Seeker
SEEKER_HEALTH_POINTS = 15
SEEKER_MAX_HEALTH_POINTS = 15
SEEKER_ARMOR = 10
SEEKER_DAMAGE = 40
SEEKER_SIZE = 20
SEEKER_ATTACK_SPEED = 0.25
SEEKER_COLOR = (0, 0, 255)
SEEKER_INITIAL_SPAWN_INTERVAL = 60 # frames
SEEKER_MINIMAL_SPAWN_INTERVAL = 300 # frames

# Wie schnell er sich maximal bewegt (gerade Linie)
SEEKER_MAX_SPEED = 10

# Wie langsam er minimal wird (in scharfen Kurven)
SEEKER_MIN_SPEED = 2

# Wie viel Grad er PRO FRAME maximal drehen kann
# 2 ist extrem träge (360/2 = 180 frames = 3 sekunden für volle Drehung)
# Versuch 4-6 für agileres Verhalten
SEEKER_MAX_TURN_DEGREES_PER_FRAME = 2

# Wie schnell sich seine Geschwindigkeit ändern kann (Pixel/Frame²)
SEEKER_ACCELERATION = 0.1

# Ab welcher Distanz zum Spieler er anfängt vorsichtiger zu drehen
SEEKER_SLOWDOWN_RADIUS = 200


# XP Shard
XP_SHARD_WIDTH = 7
XP_SHARD_HEIGHT = 14
XP_SHARD_COLOR = (128, 255, 128)
XP_SHARD_SIZE = 40
XP_SHARD_PICKUP_RANGE = 150
XP_SHARD_SCATTER_RANGE = 60
XP_SHARD_SCATTER_TIME = 60 # frames
XP_SHARD_DROP_MOVEMENT_SPEED = 3
XP_SHARD_COLLECT_MOVEMENT_SPEED = 3
XP_VALUE_PLACEHOLDER = 3